### ISSUE TITLE
Hello, is there a solution for Windows 2022?

### ISSUE THREAD

**Issue by wpf97** [antonioCoco/JuicyPotatoNG#6]
<img width="923" alt="2" src="https://github.com/antonioCoco/JuicyPotatoNG/assets/22408189/b4df9c05-a407-420d-a5ce-7e8fab024fac">
<img width="956" alt="1" src="https://github.com/antonioCoco/JuicyPotatoNG/assets/22408189/e4fae2fa-bec3-4f15-b98f-6d6e073a7504">

**Comment by antonioCoco** [comment]
JuicyPotatoNG works also on default Windows Server 2022 configurations.

Try to get a different COM port with the -s flag and use the opened port found in the -l flag.
